site_name: "Mathilde BOCQUET"

theme:
  custom_dir: overrides
  logo: images/IMG_2028.png
  name: material
  palette:
    # Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre

    # Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs           # Active la barre de menu en haut
    - navigation.tabs.sticky    # Garde le menu en haut même quand on descend
nav:
  - Accueil: index.md
  - Colles: 
      - MPSI: colles/mpsi.md
      - MP*: colles/mp.md
  - Cours et TD MPSI: cours.md
  - Agrégation:
      - Leçons: agregation/leçons.md
      - Développements: agregation/developpements.md
      - Livres utilisés: agregation/livresagreg.md
  - Ressources:
      - Sites amis: ressources/sitesamis.md
      - Ressources pour les préparationnaires: ressources/pourprepa.md
  - Motivation: motivation.md

extra:
  generator: false
  
  
  
